title: Opening The Black Bock
email: heverballesta@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 We are going to unlock the science.
baseurl: /otbb.github.io
url: https://hdballestan.github.io/otbb.github.io
twitter_username: 
github_username:  hdballestan

# Build settings
theme: academic-jekyll-theme

plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title.html
